$(document).ready(function(){
    $("#grafico1").css("opacity", 1);
    $("#grafico2").css("opacity", 0.8);
    $("#grafico3").css("opacity", 0.8);
    $("#grafico4").css("opacity", 0.8);
    $("#grafico5").css("opacity", 0.8);
    $("#auto1").show();
    $("#auto2").hide();
    $("#auto3").hide();
    $("#auto4").hide();
    $("#auto5").hide();
    $("#ley0").hide();
    $("#leyemilia").hide();
    $("#leychat").hide();
    $("#ley50").hide();
    $("#boton1").css("opacity",0.8);
    $("#boton2").css("opacity",0.8);
    $("#boton3").css("opacity",0.8);
    $("#boton4").css("opacity",0.8);
    $("#billete").hide();
    $("#billete2").hide();
    $("#lice").hide();
    $("#carcel").hide();
    $("#multa").hide();
    $("#licencia").hide();
    $("#prision").hide();
    $("#multa1").hide();
    $("#licencia1").hide();
    $("#prision1").hide();
    $("#multa2").hide();
    $("#cuadro").hide();
    $("#multa3").hide();
    $("#textocuadro1").hide();
    $("#cuadro2").hide();
    $("#textocuadro2").hide();
    $("#cuadro3").hide();
    $("#textocuadro3").hide();
    $("#cuadro4").hide();
    $("#textocuadro4").hide();

$("#boton1").click(function(){
    $("#boton1").css("opacity",1);
    $("#boton2").css("opacity",0.8);
    $("#boton3").css("opacity",0.8);
    $("#boton4").css("opacity",0.8);
    $("#grafico1").css("opacity", 0.8);
    $("#grafico2").css("opacity", 1);
    $("#grafico3").css("opacity", 0.8);
    $("#grafico4").css("opacity", 0.8);
    $("#grafico5").css("opacity", 0.8);
    $("#auto1").hide();
    $("#auto2").show();
    $("#auto3").hide();
    $("#auto4").hide();
    $("#auto5").hide();
    $("#ley0").show();
    $("#leyemilia").hide();
    $("#leychat").hide();
    $("#ley50").hide();
    $("#billete").show();
    $("#lice").show();
    $("#carcel").show();
    $("#multa").show();
    $("#licencia").show();
    $("#prision").show();
    $("#multa1").hide();
    $("#licencia1").hide();
    $("#prision1").hide();
    $("#multa2").hide();
    $("#cuadro").show();
    $("#textocuadro1").show();
    $("#cuadro2").hide();
    $("#textocuadro2").hide();
    $("#cuadro3").hide();
    $("#textocuadro3").hide();
    $("#cuadro4").hide();
    $("#textocuadro4").hide();
    $("#multa3").hide();
    $("#billete2").hide();
    
})
$("#boton2").click(function(){
    $("#boton1").css("opacity",0.8);
    $("#boton2").css("opacity",1);
    $("#boton3").css("opacity",0.8);
    $("#boton4").css("opacity",0.8);
    $("#grafico1").css("opacity", 0.8);
    $("#grafico2").css("opacity", 0.8);
    $("#grafico3").css("opacity", 1);
    $("#grafico4").css("opacity", 0.8);
    $("#grafico5").css("opacity", 0.8);
    $("#auto1").hide();
    $("#auto2").hide();
    $("#auto3").show();
    $("#auto4").hide();
    $("#auto5").hide();
    $("#ley0").hide();
    $("#leyemilia").show();
    $("#leychat").hide();
    $("#ley50").hide();
    $("#billete").show();
    $("#lice").show();
    $("#carcel").show();
    $("#multa").hide();
    $("#licencia").hide();
    $("#prision").hide();
    $("#multa1").show();
    $("#licencia1").show();
    $("#prision1").show();
    $("#multa2").hide();
    $("#cuadro").hide();
    $("#textocuadro1").hide();
    $("#cuadro2").show();
    $("#textocuadro2").show();
    $("#cuadro3").hide();
    $("#textocuadro3").hide();
    $("#cuadro4").hide();
    $("#textocuadro4").hide();
    $("#multa3").hide();
    $("#billete2").hide();
})
$("#boton3").click(function(){
    $("#boton1").css("opacity",0.8);
    $("#boton2").css("opacity",0.8);
    $("#boton3").css("opacity",1);
    $("#boton4").css("opacity",0.8);
    $("#grafico1").css("opacity", 0.8);
    $("#grafico2").css("opacity", 0.8);
    $("#grafico3").css("opacity", 0.8);
    $("#grafico4").css("opacity", 1);
    $("#grafico5").css("opacity", 0.8);
    $("#auto1").hide();
    $("#auto2").hide();
    $("#auto3").hide();
    $("#auto4").show();
    $("#auto5").hide();
    $("#ley0").hide();
    $("#leyemilia").hide();
    $("#leychat").show();
    $("#ley50").hide();
    $("#billete").hide();
    $("#billete2").show();
    $("#lice").hide();
    $("#carcel").hide();
    $("#multa").hide();
    $("#licencia").hide();
    $("#prision").hide();
    $("#multa1").hide();
    $("#licencia1").hide();
    $("#prision1").hide();
    $("#multa2").show();
    $("#cuadro").hide();
    $("#textocuadro1").hide();
    $("#cuadro2").hide();
    $("#textocuadro2").hide();
    $("#cuadro3").show();
    $("#textocuadro3").show();
    $("#cuadro4").hide();
    $("#textocuadro4").hide();
    $("#multa3").hide();
})
$("#boton4").click(function(){
    $("#boton1").css("opacity",0.8);
    $("#boton2").css("opacity",0.8);
    $("#boton3").css("opacity",0.8);
    $("#boton4").css("opacity",1);
    $("#grafico1").css("opacity", 0.8);
    $("#grafico2").css("opacity", 0.8);
    $("#grafico3").css("opacity", 0.8);
    $("#grafico4").css("opacity", 0.8);
    $("#grafico5").css("opacity", 1);
    $("#auto1").hide();
    $("#auto2").hide();
    $("#auto3").hide();
    $("#auto4").hide();
    $("#auto5").show();
    $("#ley0").hide();
    $("#leyemilia").hide();
    $("#leychat").hide();
    $("#ley50").show();
    $("#billete").hide();
    $("#billete2").show();
    $("#lice").hide();
    $("#carcel").hide();
    $("#multa").hide();
    $("#licencia").hide();
    $("#prision").hide();
    $("#multa1").hide();
    $("#licencia1").hide();
    $("#prision1").hide();
    $("#multa2").hide();
    $("#cuadro").hide();
    $("#textocuadro1").hide();
    $("#cuadro2").hide();
    $("#textocuadro2").hide();
    $("#cuadro3").hide();
    $("#textocuadro3").hide();
    $("#cuadro4").show();
    $("#textocuadro4").show();
    $("#multa3").show();
})
$("#bandera").click(function(){
    $("#boton1").css("opacity",0.8);
    $("#boton2").css("opacity",0.8);
    $("#boton3").css("opacity",0.8);
    $("#boton4").css("opacity",0.8);
    $("#grafico1").css("opacity", 1);
    $("#grafico2").css("opacity", 0.8);
    $("#grafico3").css("opacity", 0.8);
    $("#grafico4").css("opacity", 0.8);
    $("#grafico5").css("opacity", 0.8);
    $("#auto1").show();
    $("#auto2").hide();
    $("#auto3").hide();
    $("#auto4").hide();
    $("#auto5").hide();
    $("#ley0").hide();
    $("#leyemilia").hide();
    $("#leychat").hide();
    $("#ley50").hide();
    $("#billete").hide();
    $("#billete2").hide();
    $("#lice").hide();
    $("#carcel").hide();
    $("#multa").hide();
    $("#licencia").hide();
    $("#prision").hide();
    $("#multa1").hide();
    $("#licencia1").hide();
    $("#prision1").hide();
    $("#multa2").hide();
    $("#cuadro").hide();
    $("#textocuadro1").hide();
    $("#cuadro2").hide();
    $("#textocuadro2").hide();
    $("#cuadro3").hide();
    $("#textocuadro3").hide();
    $("#cuadro4").hide();
    $("#textocuadro4").hide();
    $("#multa3").hide();
})
})

//$("#boton1").mouseenter(function(){
  //  $("#boton1").css("opacity",0.8);